import React,{createContext,useContext,useEffect,useRef,useState} from 'react';
import {useAuth} from './AuthContext';
import {db} from '../services/firebase';
import {doc,getDoc,runTransaction} from 'firebase/firestore';
const Context=createContext();
export const useInvoice=()=>{const c=useContext(Context);if(!c)throw new Error('InvoiceProvider required');return c;};
const empty={clients:[],invoices:[],lastInvoiceNumber:0,senderProfile:null,revision:0};
export function InvoiceProvider({children}){
 const {user}=useAuth();const [state,setState]=useState({...empty,owner:null}),[loading,setLoading]=useState(true),[loadError,setError]=useState(''),[retry,setRetry]=useState(0);const lock=useRef(false),owner=useRef(user?.uid);owner.current=user?.uid;
 useEffect(()=>{let active=true;setLoading(true);setError('');setState({...empty,owner:user?.uid});if(!user?.uid){setLoading(false);return;}const key='invoiceData_'+user.uid;const timer=setTimeout(()=>{if(active){setLoading(false);setError('Invoices are taking too long to load. Retry when connected.');}},15000);
 (async()=>{try{let data;if(user.isGuest){data=JSON.parse(localStorage.getItem(key)||'null')||{clients:JSON.parse(localStorage.getItem('invoice_clients_'+user.uid)||'[]'),invoices:JSON.parse(localStorage.getItem('invoice_history_'+user.uid)||'[]'),lastInvoiceNumber:Number(localStorage.getItem('last_invoice_number_'+user.uid)||0),senderProfile:JSON.parse(localStorage.getItem('invoice_sender_'+user.uid)||'null')};}else{const snap=await getDoc(doc(db,'invoiceData',user.uid));data=snap.data()||{};}if(!Array.isArray(data.clients||[])||!Array.isArray(data.invoices||[]))throw new Error();if(active){setState({...empty,...data,owner:user.uid});setError('');}}catch(_){if(active)setError('Invoice records could not be loaded.');}finally{clearTimeout(timer);if(active)setLoading(false);}})();return()=>{active=false;clearTimeout(timer);};},[user?.uid,user?.isGuest,retry]);
 const current=state.owner===user?.uid?state:empty;
 async function commit(patch){if(lock.current||loading||loadError||!user?.uid||state.owner!==user.uid)throw new Error('Wait for your invoice records to load.');if(!user.isGuest&&!navigator.onLine)throw new Error('Connect before saving invoices.');lock.current=true;const uid=user.uid;const next={...current,...patch,revision:(current.revision||0)+1};delete next.owner;
 try{if(user.isGuest){const key='invoiceData_'+uid;const stored=JSON.parse(localStorage.getItem(key)||'null');if(stored&&(stored.revision||0)!==(current.revision||0))throw new Error('Invoice records changed. Reload before saving.');localStorage.setItem(key,JSON.stringify(next));}else{await runTransaction(db,async tx=>{const ref=doc(db,'invoiceData',uid);const saved=(await tx.get(ref)).data()||{};if((saved.revision||0)!==(current.revision||0))throw new Error('Invoice records changed. Reload before saving.');tx.set(ref,{...next,updatedAt:new Date().toISOString()},{merge:true});});}if(owner.current===uid)setState({...next,owner:uid});return next;}finally{lock.current=false;}}
 async function saveClient(data){const client={...data,id:data.id||crypto.randomUUID()};const clients=[...current.clients.filter(c=>c.id!==client.id),client];await commit({clients});return clients;}
 async function addInvoice(data){if(current.invoices.some(i=>String(i.invoiceNumber)===String(data.invoiceNumber)))throw new Error('Invoice number already used. Reopen the invoice form.');const item={...data,id:data.id||crypto.randomUUID(),createdAt:new Date().toISOString()};await commit({invoices:[item,...current.invoices],lastInvoiceNumber:Math.max(current.lastInvoiceNumber,Number(data.invoiceNumber)||0)});return item;}
 return <Context.Provider value={{...current,loading,loadError,retry:()=>setRetry(n=>n+1),saveClient,deleteClient:id=>commit({clients:current.clients.filter(c=>c.id!==id)}),addInvoice,deleteInvoice:id=>commit({invoices:current.invoices.filter(i=>i.id!==id)}),getNextInvoiceNumber:()=>current.lastInvoiceNumber+1,saveSenderProfile:senderProfile=>commit({senderProfile})}}>{children}</Context.Provider>;
}
