import React from 'react';
import { createRoot } from 'react-dom/client';
import { MemoryRouter } from 'react-router-dom';
import SimpleDashboard from '../../src/components/SimpleDashboard';
import AppNavigation from '../../src/components/AppNavigation';
import ExpensesOverview from '../../src/components/ExpensesOverview';
import { FixtureProvider } from './data';
import '../../src/index.css';
const now = new Date();
const today = `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;
localStorage.setItem('expenses_home-fixture-only', JSON.stringify([{ id: 'fuel', date: today, amount: 45.20, source: 'my_expense', category: 'Fuel' }]));
createRoot(document.getElementById('root')).render(<MemoryRouter initialEntries={['/app/dashboard']}><FixtureProvider><main style={{padding:'16px 16px 90px'}}>{new URLSearchParams(location.search).get('screen') === 'expenses' ? <ExpensesOverview /> : <SimpleDashboard />}</main><AppNavigation /></FixtureProvider></MemoryRouter>);
