import React from 'react';
import {beforeEach,expect,it,vi} from 'vitest';
import {render,screen,fireEvent} from '@testing-library/react';
import StatementReview from '../components/StatementReview';
import {createStatementReview,reviewIssues,confirmedReview} from '../features/statements/reviewModel';
const period={id:'2026-08-17_2026-09-13',start:'2026-08-17',end:'2026-09-13'};
const extracted={periodStart:period.start,periodEnd:period.end,currency:'GBP',taxBasis:'excluded',contractorPayout:4217.69,statementAmount:5499.55,contractorFee:329.97,contractorCharges:951.89,charges:[{label:'lease',amount:525},{label:'other',amount:426.89}]};
const approved=()=>({...createStatementReview(extracted),reviewed:true,items:createStatementReview(extracted).items.map(i=>({...i,reviewed:true}))});
beforeEach(()=>{URL.createObjectURL=vi.fn(()=> 'blob:test');URL.revokeObjectURL=vi.fn();});
it('requires charge and overall review without inventing confidence percentages',()=>{expect(reviewIssues(createStatementReview(extracted),period).length).toBe(3);expect(reviewIssues(approved(),period)).toEqual([]);});
it('uses integer pennies for waterfall and detects missing or inconsistent charge items',()=>{const d=approved();expect(confirmedReview(d).payoutPence).toBe(421769);d.items[0].amount='526';expect(reviewIssues(d,period).some(i=>i.field==='charges')).toBe(true);d.payout='4218';expect(reviewIssues(d,period).some(i=>i.field==='payout')).toBe(true);});
it('blocks period/currency/tax mismatches and unknown mandatory payout',()=>{for(const patch of [{start:'2026-08-18'},{currency:'EUR'},{taxBasis:'included'},{taxBasis:'unknown'},{payout:''}])expect(reviewIssues({...approved(),...patch},period).length).toBeGreaterThan(0);});
it('permits payout-only comparison when optional subtotals are absent',()=>{expect(reviewIssues({...approved(),gross:'',fee:'',charges:'',items:[]},period)).toEqual([]);});
it('keeps source transient and releases its object URL on exit',()=>{const view=render(<StatementReview draft={approved()} onChange={()=>{}} period={period} periods={[period]} file={new File(['image'],'statement.png',{type:'image/png'})} ready onContinue={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'View original statement'}));expect(screen.getByAltText('Original statement for checking extracted figures')).toHaveAttribute('src','blob:test');view.unmount();expect(URL.revokeObjectURL).toHaveBeenCalledWith('blob:test');});
it('correction clears confirmation and never invokes another AI extraction',()=>{const changed=vi.fn(),next=vi.fn();render(<StatementReview draft={approved()} onChange={changed} period={period} periods={[period]} ready onContinue={next}/>);fireEvent.change(screen.getByLabelText('Final contractor payout (£)'),{target:{value:'4210'}});expect(changed).toHaveBeenCalledWith(expect.objectContaining({payout:'4210',reviewed:false}));expect(next).not.toHaveBeenCalled();});
