import React, { useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Package, Plus, Minus, X, Briefcase, Check } from "lucide-react";
import { useData } from "../contexts/DataContext";
import { calculateDayEarnings } from "../features/payperiod/payStructure";
import { Money } from "./ui/money";
const localISO=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;};
export default function DailyQuickEntry({open,onClose,onSaved}){
 const {logs=[],updateLogs,paymentConfig}=useData(); const [stops,setStops]=useState(""); const [extraWork,setExtraWork]=useState(false); const [extraType,setExtraType]=useState("Collection"); const [extraAmount,setExtraAmount]=useState(""); const [notes,setNotes]=useState(""); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const today=localISO();
 const expected=useMemo(()=>calculateDayEarnings(paymentConfig,{quantity:Number(stops)||0})+(extraWork?(Number(extraAmount)||0):0),[paymentConfig,stops,extraWork,extraAmount]);
 const adjust=n=>setStops(String(Math.max(0,(Number(stops)||0)+n)));
 const save=async()=>{const qty=Number(stops);if(!Number.isFinite(qty)||qty<=0){setError("Enter today's deliveries first.");return;}setSaving(true);setError("");try{const extra=extraWork?(Number(extraAmount)||0):0;const newLog={id:Date.now(),date:today,stops:qty,extra,total:calculateDayEarnings(paymentConfig,{quantity:qty})+extra,notes:extraWork?`${extraType}${notes?`: ${notes}`:""}`:"",extraType:extraWork?extraType:null,timestamp:new Date().toISOString()};await updateLogs([newLog,...logs.filter(l=>l.date!==today)].sort((a,b)=>b.date.localeCompare(a.date)));localStorage.setItem(`daily-quick-entry-${today}`,"saved");if(navigator.vibrate)navigator.vibrate([25,20,25]);onSaved?.(newLog);}catch(e){setError("Couldn't save. Your entry is still here — please try again.");}finally{setSaving(false);}};
 return <AnimatePresence>{open&&<motion.div className="fixed inset-0 z-[80] flex items-end justify-center bg-black/70 px-3 pb-[max(12px,env(safe-area-inset-bottom))] pt-[max(12px,env(safe-area-inset-top))] backdrop-blur-sm sm:items-center" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div role="dialog" aria-modal="true" aria-label="Quick entry" className="max-h-[calc(100dvh-24px)] w-full max-w-md overflow-y-auto rounded-[28px] border border-[#27324a] bg-[#0d1422] p-5 shadow-2xl sm:p-6" initial={{y:36,opacity:0,scale:.98}} animate={{y:0,opacity:1,scale:1}} exit={{y:28,opacity:0}} transition={{type:"spring",damping:28,stiffness:320}}>
 <div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-[#9aa6bd]">Good {new Date().getHours()<12?"morning":new Date().getHours()<18?"afternoon":"evening"}</p><h2 className="mt-1 text-2xl font-bold">Let's log today's work</h2></div><button onClick={onClose} aria-label="Not now" className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl border border-[#2a3550] bg-[#131c2d] text-[#9aa6bd]"><X/></button></div>
 <div className="mt-5 rounded-2xl border border-[#26314a] bg-[#111827] p-4"><div className="flex items-center gap-3"><span className="rounded-xl bg-blue-500/10 p-2 text-blue-400"><Package/></span><div><div className="font-semibold">Today's deliveries</div><div className="text-xs text-[#7f8ba3]">{new Date(today+"T12:00:00").toLocaleDateString("en-GB",{weekday:"short",day:"numeric",month:"short",year:"numeric"})}</div></div></div><label className="mt-5 block text-center text-sm font-semibold">How many deliveries did you complete today?</label><div className="mt-3 flex items-center gap-3"><button onClick={()=>adjust(-1)} className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-[#182238] text-[#aeb8ca]"><Minus/></button><input autoFocus inputMode="numeric" type="number" min="0" value={stops} onChange={e=>setStops(e.target.value)} placeholder="0" className="h-16 min-w-0 flex-1 rounded-2xl border border-[#34415f] bg-[#0a101b] text-center text-3xl font-bold tabular-nums outline-none focus:border-[#7567ff] focus:ring-2 focus:ring-[#7567ff]/20"/><button onClick={()=>adjust(1)} className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-[#182238] text-[#aeb8ca]"><Plus/></button></div>{Number(stops)>0&&<div className="mt-3 text-center text-xs text-[#8e9ab2]">Expected today <strong className="ml-1 text-emerald-400"><Money amount={expected}/></strong></div>}</div>
 <div className="mt-3 overflow-hidden rounded-2xl border border-[#26314a] bg-[#111827]"><button type="button" onClick={()=>setExtraWork(v=>!v)} className="flex min-h-[64px] w-full items-center gap-3 p-4 text-left"><Briefcase className="h-5 w-5 text-[#8f83ff]"/><span className="flex-1"><span className="block text-sm font-semibold">Did you do any extra work today?</span><span className="block text-xs text-[#7f8ba3]">Collections, returns or another paid job</span></span><span className={`grid h-7 w-7 place-items-center rounded-lg border ${extraWork?"border-emerald-400 bg-emerald-400 text-[#07110e]":"border-[#46516a] bg-[#0a101b]"}`}>{extraWork&&<Check className="h-4 w-4"/>}</span></button><AnimatePresence>{extraWork&&<motion.div initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden"><div className="space-y-3 border-t border-[#26314a] p-4"><label className="block text-xs text-[#8e9ab2]">Type of extra work<select value={extraType} onChange={e=>setExtraType(e.target.value)} className="mt-1 h-12 w-full rounded-xl border border-[#34415f] bg-[#0a101b] px-3 text-sm text-white"><option>Collection</option><option>Return</option><option>Extra route</option><option>Other</option></select></label><label className="block text-xs text-[#8e9ab2]">Extra amount (£)<input inputMode="decimal" value={extraAmount} onChange={e=>setExtraAmount(e.target.value)} placeholder="0.00" className="mt-1 h-12 w-full rounded-xl border border-[#34415f] bg-[#0a101b] px-3 text-base text-white outline-none focus:border-[#7567ff]"/></label><label className="block text-xs text-[#8e9ab2]">Notes <span className="text-[#5f6a80]">(optional)</span><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What did you do?" className="mt-1 h-12 w-full rounded-xl border border-[#34415f] bg-[#0a101b] px-3 text-sm text-white outline-none focus:border-[#7567ff]"/></label></div></motion.div>}</AnimatePresence></div>
 {error&&<p className="mt-3 text-sm text-red-400">{error}</p>}<button onClick={save} disabled={saving||!stops} className="mt-4 h-14 w-full rounded-2xl bg-gradient-to-r from-[#6657f5] to-[#806cff] text-base font-bold text-white shadow-lg shadow-[#7567ff]/20 disabled:opacity-40">{saving?"Saving…":"Save Entry"}</button><button onClick={onClose} className="mt-2 h-10 w-full text-xs font-medium text-[#7f8ba3]">Not now</button>
 </motion.div></motion.div>}</AnimatePresence>;
}