import React,{useState} from 'react';
import {Link,useLocation} from 'react-router-dom';
import {useData} from '../contexts/DataContext';
import DailyQuickEntry from './DailyQuickEntry';
import {money} from '../features/home/homeModel';
import {isoDate} from '../features/payperiod/periods';
function workLabel(r){const model=r.payStructureSnapshot?.model||r.payModel;const [quantity,unit]=model==='per_day'?[r.quantity??1,'day']:model==='hourly'?[r.hours??r.quantity,'hours']:model==='per_mile'?[r.miles??r.quantity,'miles']:[r.stops??r.quantity,'stops'];return `${quantity??'—'} ${unit}`;}
export default function EntriesPage(){
 const {logs=[],loading,loadError,updateLogs}=useData();const loc=useLocation();const [query,setQuery]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[editing,setEditing]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const rows=logs.filter(r=>(!from||r.date>=from)&&(!to||r.date<=to)&&(!query||`${r.date} ${r.stops??''} ${r.notes||''}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>b.date.localeCompare(a.date));
 async function remove(row){if(!window.confirm('Delete this work record? Related pay checks will need reviewing.'))return;setBusy(true);setError('');try{await updateLogs(logs.filter(r=>r.id!==row.id),{strict:true});}catch(_){setError('Could not delete this record. Please retry.');}finally{setBusy(false);}}
 return <div className="home-screen st-page"><header className="home-row"><div><h1>Work records</h1><p className="home-muted">Your independent daily ledger.</p></div><button className="home-primary" onClick={()=>setEditing(isoDate(new Date()))}>+ Entry</button></header>{loc.state?.walkthrough?<div className="home-card" data-tour="entry-example"><h2>Example work day</h2><p>150 stops · 185 parcels</p><p className="home-muted">Temporary tour example — nothing here is saved.</p></div>:<><details className="home-card"><summary>Search and filter</summary><label className="home-field">Search date, stops or notes<input value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="review-fields"><label className="home-field">From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="home-field">To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><button className="home-text-button" onClick={()=>{setQuery('');setFrom('');setTo('');}}>Clear filters</button></details>{loading?<div className="home-skeleton" role="status" aria-label="Loading work records"/>:loadError?<p role="alert" className="home-banner">{loadError}</p>:rows.length?<div className="st-list" data-tour="entries-ledger">{rows.map(r=><article className="home-card" key={r.id}><div className="home-row"><div><h2>{r.date}</h2><p className="home-muted">{workLabel(r)}{r.totalParcels!=null?` · ${r.totalParcels} parcels`:''}</p></div><div><strong>{r.total!=null&&r.total!==''&&Number.isFinite(Number(r.total))?money(Number(r.total)):'Unavailable'}</strong><p className="home-muted text-sm">Gross · Estimated</p></div></div>{r.notes&&<p className="home-muted mt-3">{r.notes}</p>}<div className="st-actions mt-3"><button className="home-secondary" disabled={busy} onClick={()=>setEditing(r.date)}>Edit record</button><button className="home-text-button home-error" disabled={busy} onClick={()=>remove(r)}>Delete</button></div></article>)}</div>:<div className="st-empty"><h2>{logs.length?'No matching records':'No work recorded yet'}</h2><p>Log a day to start building your independent record.</p></div>}</>}{error&&<p role="alert" className="home-error">{error}</p>}<Link className="home-text-button" to="/app/dashboard">Back to Home</Link><DailyQuickEntry open={!!editing} initialDate={editing} onClose={()=>setEditing(null)} onSaved={()=>setEditing(null)}/></div>;
}
