import React,{useEffect,useRef,useState} from 'react';
import {useReducedMotion,motion} from 'framer-motion';
import {PAY_MODELS} from '../features/payperiod/payStructure';
import {blankPay,rateFields,rateLabels,validatePaySetup,cleanPaySetup,payExample} from '../features/payperiod/paySetupModel';
import {money} from '../features/home/homeModel';
import {trackProductEvent as track} from '../services/productAnalytics';
import '../styles/pay-setup.css';
export default function PayStructureEditor({initialConfig,onConfirm,onBack}){
 const [config,setConfig]=useState(()=>initialConfig?{...initialConfig,excessParcelRate:initialConfig.excessParcelRate??0,contractorFeePercent:initialConfig.contractorFeePercent??''}:blankPay('flat_stops'));
 const [feeOn,setFeeOn]=useState(initialConfig?initialConfig.contractorFeePercent!==0:false),[parcelOn,setParcelOn]=useState(Number(initialConfig?.excessParcelRate)>0);
 const [saving,setSaving]=useState(false),[error,setError]=useState('');const drafts=useRef({}),lock=useRef(false);const reduced=useReducedMotion();
 const [baseline]=useState(()=>JSON.stringify(config));const dirty=JSON.stringify(config)!==baseline || feeOn!==(initialConfig?initialConfig.contractorFeePercent!==0:false) || parcelOn!==(Number(initialConfig?.excessParcelRate)>0);
 useEffect(()=>{if(!dirty)return;const guard=e=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);
 const change=(key,value)=>{setConfig(c=>({...c,[key]:value}));setError('');};
 function model(value){drafts.current[config.model]=config;const next=drafts.current[value]||{...blankPay(value),contractorFeePercent:config.contractorFeePercent};setConfig(next);setParcelOn(Number(next.excessParcelRate)>0);track('pay_model_selected');}
 const field=(label,key,value,onChange)=> <label className="home-field" key={key}>{label}<input inputMode="decimal" value={value??''} onChange={e=>onChange?onChange(e.target.value):change(key,e.target.value)} /></label>;
 const parcelRelevant=['flat_stops','tiered_stops','sliding_scale'].includes(config.model);
 const candidate={...config,contractorFeePercent:feeOn?config.contractorFeePercent:0,excessParcelRate:parcelOn&&parcelRelevant?config.excessParcelRate:0};
 const example=payExample(candidate);
 async function submit(e){e.preventDefault();if(lock.current)return;const problem=validatePaySetup(candidate);if(problem){setError(problem);track('pay_setup_validation_failed');return;}lock.current=true;setSaving(true);setError('');try{await onConfirm(cleanPaySetup(candidate));}catch(err){setError(err?.message?.includes('changed elsewhere')?'Pay settings changed on another device. Reload before saving.':'Could not save. Your settings are still here. Connect and retry.');}finally{lock.current=false;setSaving(false);}}
 function band(axis,index,value){const values=[...config[axis]];values[index]=value;change(axis,values);}
 function addBand(axis){const values=[...config[axis],''];const grid=config.rateMatrix.map(r=>[...r]);if(axis==='stopBands')grid.push(config.mileBands.map(()=>''));else grid.forEach(r=>r.push(''));setConfig(c=>({...c,[axis]:values,rateMatrix:grid}));}
 function removeBand(axis,index){const values=config[axis].filter((_,i)=>i!==index);const grid=axis==='stopBands'?config.rateMatrix.filter((_,i)=>i!==index):config.rateMatrix.map(row=>row.filter((_,i)=>i!==index));setConfig(c=>({...c,[axis]:values,rateMatrix:grid}));}
 return <motion.form className="home-screen pay-setup" onSubmit={submit} noValidate initial={{opacity:0,y:reduced?0:6}} animate={{opacity:1,y:0}} transition={{duration:reduced?0:.2}}>
 <h3 className="text-xl font-bold">Review your pay structure</h3><p className="home-muted">Check every field. Nothing is saved until you confirm.</p>
 <fieldset disabled={saving} className="pay-fields">
 <label className="home-field">How are you paid?<select value={config.model} onChange={e=>model(e.target.value)}>{PAY_MODELS.map(m=><option key={m.id} value={m.id}>{m.label}</option>)}</select></label>
 {rateFields[config.model]&&field(rateLabels[config.model]+' (£)',rateFields[config.model],config[rateFields[config.model]])}
 {config.model==='per_mile'&&field('Daily base payment (£)','baseFee',config.baseFee??0)}
 {config.model==='tiered_stops'&&<section className="home-card space-y-3"><h4 className="font-bold">Tiered rates</h4><p className="home-muted text-sm">Each block of stops uses its own rate. Later rates do not change earlier stops.</p>{config.thresholds.map((tier,i)=><div className="pay-tier" key={i}>{i<config.thresholds.length-1?field('Up to stop','limit'+i,tier.stopCount,v=>change('thresholds',config.thresholds.map((t,j)=>j===i?{...t,stopCount:v}:t))):<p>All remaining stops</p>}{field('Rate (£/stop)','tier'+i,tier.rate,v=>change('thresholds',config.thresholds.map((t,j)=>j===i?{...t,rate:v}:t)))}{i<config.thresholds.length-1&&config.thresholds.length>2&&<button type="button" className="home-text-button" onClick={()=>change('thresholds',config.thresholds.filter((_,j)=>j!==i))}>Remove tier {i+1}</button>}</div>)}<button type="button" className="home-secondary" disabled={config.thresholds.length>=20} onClick={()=>change('thresholds',[...config.thresholds.slice(0,-1),{stopCount:'',rate:''},config.thresholds.at(-1)])}>Add tier</button></section>}
 {config.model==='sliding_scale'&&<section className="home-card space-y-3"><h4 className="font-bold">Sliding scale · rate for all stops</h4><p className="home-muted text-sm">Uses the nearest stop/mileage band; ties use the lower band. Confirm this matches your agreement.</p>{['stopBands','mileBands'].map(axis=><div key={axis}><h5>{axis==='stopBands'?'Stop bands':'Mileage bands'}</h5>{config[axis].map((v,i)=><div className="home-row" key={i}>{field(`${axis==='stopBands'?'Stop':'Mileage'} band ${i+1}`,axis+i,v,next=>band(axis,i,next))}{config[axis].length>1&&<button type="button" className="home-text-button" onClick={()=>removeBand(axis,i)}>Remove</button>}</div>)}<button type="button" className="home-secondary" disabled={config[axis].length>=20} onClick={()=>addBand(axis)}>Add {axis==='stopBands'?'stop':'mileage'} band</button></div>)}<div className="pay-grid-scroll" tabIndex={0} role="region" aria-label="Sliding rate grid"><table><caption>Rate per stop (£)</caption><thead><tr><th>Stops / miles</th>{config.mileBands.map((m,j)=><th key={j}>{m||'—'}</th>)}</tr></thead><tbody>{config.rateMatrix.map((row,i)=><tr key={i}><th>{config.stopBands[i]||'—'}</th>{row.map((v,j)=><td key={j}><input aria-label={`Rate for stop band ${i+1}, mileage band ${j+1}`} inputMode="decimal" value={v} onChange={e=>change('rateMatrix',config.rateMatrix.map((r,a)=>r.map((cell,b)=>a===i&&b===j?e.target.value:cell)))}/></td>)}</tr>)}</tbody></table></div></section>}
 {parcelRelevant&&<section className="home-card space-y-3"><label className="pay-toggle"><span>Excess parcel pay</span><input type="checkbox" checked={parcelOn} onChange={e=>{setParcelOn(e.target.checked);if(e.target.checked&&!Number(config.excessParcelRate))change('excessParcelRate','');}}/></label>{parcelOn&&field('Per excess parcel (£)','excessParcelRate',config.excessParcelRate)}<p className="home-muted text-sm">Parcels above your stop count.</p></section>}
 <section className="home-card space-y-3"><label className="pay-toggle"><span>Contractor deduction</span><input type="checkbox" checked={feeOn} onChange={e=>{setFeeOn(e.target.checked);if(e.target.checked&&!Number(config.contractorFeePercent))change('contractorFeePercent','');}}/></label>{feeOn&&field('Percentage of work earnings (%)','contractorFeePercent',config.contractorFeePercent)}<p className="home-muted text-sm">Taken from work earnings, including extras, before business expenses. {feeOn?'':'No percentage deduction.'}</p></section>
 </fieldset>
 <section className="home-card space-y-3" aria-live="polite"><h4 className="font-bold">Example only · Not saved</h4>{example?<><p>{example.quantity} {PAY_MODELS.find(m=>m.id===config.model)?.primary.unit}{parcelRelevant&&parcelOn?' + 38 excess parcels':''}{config.model==='sliding_scale'?' · 80 miles':''}</p><dl className="home-breakdown"><div><dt>Work earnings</dt><dd>{money(example.gross)}</dd></div><div><dt>Contractor fee</dt><dd>{money(-example.fee)}</dd></div><div><dt>After contractor fee</dt><dd className="home-money">{money(example.after)}</dd></div></dl><p className="home-muted text-sm">Before expenses and personal tax.</p></>:<p className="home-muted">Complete the fields to see an example.</p>}</section>
 <p className="home-muted text-sm">Saved days keep their original rates. Fixed contractor charges belong in Expenses.</p>
 {error&&<p role="alert" className="home-error">{error}</p>}
 <footer className="pay-save"><button className="home-primary w-full" disabled={saving}>{saving?'Saving…':'Confirm pay structure'}</button><button type="button" disabled={saving} className="home-text-button w-full" onClick={()=>{if(!dirty||window.confirm('Discard changes to this review?'))onBack();}}>Back to description</button></footer>
 </motion.form>;
}
