import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {useData} from '../contexts/DataContext';
import {isoDate,listPeriods} from '../features/payperiod/periods';
import {money} from '../features/home/homeModel';
export default function PeriodHistoryV4({compact=false}){
 const {logs=[],payPeriodAnchor,periodRecords={},loading,loadError,updatePayPeriodAnchor}=useData();const [date,setDate]=useState(payPeriodAnchor||''),[busy,setBusy]=useState(false),[error,setError]=useState('');const today=isoDate(new Date());const periods=listPeriods(logs,payPeriodAnchor||today,compact?3:13);
 async function save(){if(payPeriodAnchor&&date!==payPeriodAnchor&&!window.confirm('Change pay-period dates? Existing checks remain attached to their original periods.'))return;setBusy(true);setError('');try{await updatePayPeriodAnchor(date);}catch(_){setError('Could not save pay-period dates. Connect and retry.');}finally{setBusy(false);}}
 return <div className="home-screen st-page">{!compact&&<><p className="home-muted">Work records grouped into your four-week pay periods.</p><details className="home-card" open={!payPeriodAnchor||undefined}><summary>Pay-period dates</summary><p className="home-muted text-sm">Enter the first day of a known four-week period. Selecting a period elsewhere never changes this setup.</p><label className="home-field mt-3">Period start<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="home-primary mt-3" disabled={!date||busy||date===payPeriodAnchor} onClick={save}>{busy?'Saving…':'Save period dates'}</button>{error&&<p role="alert" className="home-error">{error}</p>}</details></>}{loading?<div className="home-skeleton" role="status" aria-label="Loading periods"/>:loadError?<p role="alert">{loadError}</p>:!payPeriodAnchor?<p className="home-banner">Set your dates to group work correctly.</p>:periods.map(p=>{const r=periodRecords[p.id];const status=r?.needsReview?'Needs recheck':r?.status==='reconciled'?'Reconciled · Open to verify':r?.payoutComparison?'Checked · Open to verify':p.end<today?'Awaiting statement':'Tracking';return <Link className="st-list-row" key={p.id} to="/app/money" state={p}><span className="st-grow"><strong>{p.start} – {p.end}</strong><small>{p.daysLogged} days · {p.stops} stops</small><span className="st-badge">{status}</span></span><span><strong>{money(p.expected)}</strong><small>Gross · Estimated</small></span></Link>;})}</div>;
}
