import React,{useEffect,useState} from 'react';
import {Link,useLocation,useNavigate} from 'react-router-dom';
import {updateProfile} from 'firebase/auth';
import {doc,setDoc} from 'firebase/firestore';
import {ref,uploadBytes,getDownloadURL} from 'firebase/storage';
import {auth,db,storage} from '../services/firebase';
import {useTheme} from '../contexts/ThemeContext';
import {useData} from '../contexts/DataContext';
import {useInvoice} from '../contexts/InvoiceContext';
import useExpenses from '../hooks/useExpenses';
import {subscribeToEntitlement,openBillingPortal} from '../services/billing';
import {downloadRecords,deleteAccountRecords} from '../services/accountData';
import {trackProductEvent as track} from '../services/productAnalytics';
export default function Profile({userId,user,onLogout}){
 const nav=useNavigate(),loc=useLocation(),data=useData(),invoice=useInvoice(),costs=useExpenses(),{themePreference,setThemePreference}=useTheme();const [name,setName]=useState(user.displayName||''),[photo,setPhoto]=useState(user.photoURL||''),[ent,setEnt]=useState(null),[entRetry,setEntRetry]=useState(0),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[deleting,setDeleting]=useState(false),[confirmation,setConfirmation]=useState(''),[consent,setConsent]=useState(()=>{try{return localStorage.getItem('analytics-consent')==='granted';}catch(_){return false;}});const guest=user.isGuest||auth.currentUser?.isAnonymous;
 useEffect(()=>{setEnt(null);if(guest){setEnt({isPro:false});return;}return subscribeToEntitlement(userId,s=>{setEnt(s);if(s.isPro&&new URLSearchParams(loc.search).get('billing')==='success')track('subscription_completed');});},[userId,guest,loc.search,entRetry]);
 async function action(id,fn){if(busy)return;setBusy(id);setError('');setNotice('');try{await fn();}catch(e){setError(e?.message||'Could not complete this action. Please retry.');}finally{setBusy('');}}
 async function saveName(){if(!name.trim())throw new Error('Enter a display name.');if(guest)throw new Error('Use a permanent account to save profile changes.');await setDoc(doc(db,'users',userId),{displayName:name.trim().slice(0,80)},{merge:true});await updateProfile(auth.currentUser,{displayName:name.trim().slice(0,80)});setNotice('Profile saved.');}
 async function picture(file){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>2*1024*1024)throw new Error('Choose a JPEG, PNG or WebP under 2 MB.');const object=ref(storage,'users/'+userId+'/profile/photo');await uploadBytes(object,file,{contentType:file.type});const url=await getDownloadURL(object);await setDoc(doc(db,'users',userId),{photoURL:url},{merge:true});await updateProfile(auth.currentUser,{photoURL:url});setPhoto(url);setNotice('Profile picture saved.');}
 function analytics(next){localStorage.setItem('analytics-consent',next?'granted':'denied');setConsent(next);window.dispatchEvent(new Event('analytics-consent-changed'));}
 return <div className="home-screen st-page" style={{maxWidth:680}}><header className="home-row"><div><h1>Profile</h1><p className="home-muted">Your account, pay setup and preferences.</p></div>{photo?<img src={photo} alt="Your profile" className="w-14 h-14 rounded-full object-cover"/>:<span className="home-icon" aria-hidden="true">{(name||'D')[0]}</span>}</header>{notice&&<p role="status" className="home-banner">{notice}</p>}{error&&<p role="alert" className="home-banner home-error">{error}</p>}{new URLSearchParams(loc.search).get('billing')==='success'&&!ent?.isPro&&<p role="status" className="home-banner">Waiting for subscription confirmation from the billing service. Access updates only after server confirmation.</p>}
 {guest&&<section className="home-card"><h2>Guest account</h2><p className="home-muted">Your guest work records are stored on this device. Export them before changing accounts; account transfer is not automatic.</p><button className="home-secondary mt-3" disabled={!!busy} onClick={()=>action('signin',async()=>{await auth.signOut();nav('/login');})}>Sign in to a permanent account</button></section>}
 <Link className="st-list-row" to="/app/settings"><span className="st-grow"><strong>Pay structure</strong><small>Describe your pay in any language, or edit it manually.</small></span><span>→</span></Link><Link className="st-list-row" to="/app/periods"><span className="st-grow"><strong>Pay-period dates</strong><small>Set your four-week cycle and view previous periods.</small></span><span>→</span></Link>
 <section className="home-card"><h2>Appearance</h2><div className="st-actions mt-3">{['dark','light','system'].map(t=><button key={t} className={themePreference===t?'home-primary':'home-secondary'} aria-pressed={themePreference===t} onClick={()=>setThemePreference(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div></section>
 <details className="home-card"><summary>Edit profile</summary><label className="home-field">Display name<input value={name} maxLength={80} onChange={e=>setName(e.target.value)} disabled={guest||!!busy}/></label><button className="home-primary mt-3" disabled={guest||!!busy||!name.trim()} onClick={()=>action('profile',saveName)}>{busy==='profile'?'Saving…':'Save profile'}</button><label className="home-field mt-4">Profile photo · Optional<input type="file" accept="image/jpeg,image/png,image/webp" disabled={guest||!!busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';action('photo',()=>picture(file));}}/></label></details>
 <section className="home-card"><h2>Stop Tracker Pro</h2><p className="home-muted">{ent?.unavailable?'Subscription status unavailable. Retry when connected.':ent?.isPro?'Your Pro subscription is active.':ent?'Optional AI tools and full route optimisation.':'Checking subscription status…'}</p><button className="home-secondary w-full mt-3" disabled={!!busy||!ent} onClick={()=>ent?.unavailable?setEntRetry(n=>n+1):ent?.isPro?action('billing',openBillingPortal):nav('/app/upgrade')}>{busy==='billing'?'Opening billing…':ent?.unavailable?'Retry subscription status':ent?.isPro?'Manage subscription':'View Pro'}</button></section>
 <section className="home-card"><h2>Privacy and records</h2><label className="check-basis"><input type="checkbox" checked={consent} onChange={e=>analytics(e.target.checked)}/><span>Share product usage events to help improve Stop Tracker. No earnings, addresses or document contents. No session recording.</span></label><button className="home-secondary w-full" disabled={data.loading||invoice.loading||costs.loading||!!data.loadError||!!invoice.loadError||!!costs.error} onClick={()=>action('export',async()=>downloadRecords({work:data.logs,payStructure:data.paymentConfig,payPeriodAnchor:data.payPeriodAnchor,periods:data.periodRecords,expenses:costs.expenses,recurringCosts:costs.rules,invoices:invoice.invoices,clients:invoice.clients,senderProfile:invoice.senderProfile}))}>Export my records</button><p className="home-muted text-sm mt-2">Downloads a JSON record to this device. Receipt images and original statements are not included.</p><div className="st-actions"><Link className="home-text-button" to="/app/privacy">Privacy</Link><Link className="home-text-button" to="/app/terms">Terms</Link><Link className="home-text-button" to="/app/contact">Help</Link></div></section>
 <button className="home-secondary w-full" disabled={!!busy} onClick={()=>action('logout',onLogout)}>Sign out</button><details className="home-card" open={deleting||undefined}><summary onClick={()=>setDeleting(!deleting)}>Delete account</summary><p className="home-muted">Permanently remove your Stop Tracker account and its stored records. Downloaded copies and records held by payment providers are separate. Cancel any active subscription first.</p><label className="home-field mt-3">Type DELETE to confirm<input value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="off"/></label><button className="home-secondary home-error w-full mt-3" disabled={confirmation!=='DELETE'||!!busy} onClick={()=>action('delete',async()=>{await deleteAccountRecords(userId);await onLogout();})}>{busy==='delete'?'Deleting account…':'Delete account and records'}</button></details></div>;
}
