import React,{useEffect,useRef,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {MapPin,ArrowUp,ArrowDown,Trash2,Locate} from 'lucide-react';
import {useAuth} from '../contexts/AuthContext';
import GoogleRouteMap from './GoogleRouteMap';
import RouteMap from './RouteMap';
import {searchAddresses,computeBiasCenter,searchPostcodes,isPostcodeLike,resolvePostcode} from '../services/addressSearch';
import {resolvePlace} from '../services/googlePlaces';
import {optimizeRouteGoogle} from '../services/googleRoutes';
import {getPremiumStatus} from '../services/premium';
import {trackProductEvent as track} from '../services/productAnalytics';
const valid=a=>a?.latitude!=null&&a.latitude!==''&&a.longitude!=null&&a.longitude!==''&&Number.isFinite(Number(a.latitude))&&Math.abs(Number(a.latitude))<=90&&Number.isFinite(Number(a.longitude))&&Math.abs(Number(a.longitude))<=180;
export default function RoutePlanner(){
 const {user}=useAuth(),nav=useNavigate();const [addresses,setAddresses]=useState([]),[query,setQuery]=useState(''),[suggestions,setSuggestions]=useState([]),[searching,setSearching]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[result,setResult]=useState(null),[status,setStatus]=useState(null),[saved,setSaved]=useState([]),[name,setName]=useState(''),[retry,setRetry]=useState(0);const lock=useRef(false),generation=useRef(0);const key='savedRoutes_'+user?.uid;
 useEffect(()=>{generation.current++;lock.current=false;setBusy('');setQuery('');setSuggestions([]);setStatus(null);setAddresses([]);setResult(null);setSaved([]);try{const rows=JSON.parse(localStorage.getItem(key)||'[]');setSaved(rows.filter(r=>Array.isArray(r.addresses)&&r.addresses.every(valid)));}catch(_){setError('Saved routes could not be read.');}return()=>{generation.current++;};},[key]);
 useEffect(()=>{let active=true;getPremiumStatus().then(s=>{if(typeof s?.isPro!=='boolean'||!Number.isInteger(s?.routeOptimizationUses)||s.routeOptimizationUses<0)throw new Error('Invalid status');if(active)setStatus(s);}).catch(()=>{if(active)setStatus(null);});return()=>{active=false;};},[retry,user?.uid]);
 useEffect(()=>{if(query.trim().length<3){setSuggestions([]);setSearching(false);return;}const controller=new AbortController();let active=true;setSuggestions([]);setSearching(true);const timer=setTimeout(async()=>{try{const rows=isPostcodeLike(query)?(await searchPostcodes(query,controller.signal)).map(postcode=>({address:postcode,postcode,isPostcodeSuggestion:true})):await searchAddresses(query,computeBiasCenter(addresses),controller.signal);if(active)setSuggestions(rows);}catch(e){if(active&&e.name!=='AbortError')setError('Address search is unavailable. Check your connection and retry.');}finally{if(active)setSearching(false);}},450);return()=>{active=false;clearTimeout(timer);controller.abort();};},[query]);
 function change(rows){setAddresses(rows);setResult(null);setNotice('');}
 async function add(item){if(lock.current||addresses.length>=200)return;lock.current=true;const epoch=generation.current;setBusy('address');setError('');try{const resolved=item.needsResolve?await resolvePlace(item.placeId,new AbortController().signal):item.isPostcodeSuggestion?await resolvePostcode(item.postcode,new AbortController().signal):item;const next={...resolved,address:resolved.address||resolved.postcode||item.address,id:crypto.randomUUID()};if(epoch!==generation.current)return;if(!valid(next))throw new Error();change([...addresses,next]);setQuery('');setSuggestions([]);track('route_stop_added');if(!addresses.length)track('route_started');}catch(_){if(epoch===generation.current)setError('Could not add that address. Try another result.');}finally{if(epoch===generation.current){lock.current=false;setBusy('');}}}
 async function locate(){if(lock.current)return;lock.current=true;const epoch=generation.current;setBusy('location');setError('');try{const p=await new Promise((res,rej)=>navigator.geolocation?navigator.geolocation.getCurrentPosition(res,rej,{timeout:10000,maximumAge:30000}):rej());if(epoch!==generation.current)return;change([{id:crypto.randomUUID(),address:'My start location',latitude:p.coords.latitude,longitude:p.coords.longitude},...addresses]);}catch(_){if(epoch===generation.current)setError('Location unavailable. Search for your start address instead.');}finally{if(epoch===generation.current){lock.current=false;setBusy('');}}}
 async function optimize(){if(lock.current||addresses.length<2)return;if(status&&!status.isPro&&status.routeOptimizationUses>=3){nav('/app/upgrade');return;}lock.current=true;const epoch=generation.current;setBusy('optimizing');setError('');track('route_optimise_clicked');try{const r=await optimizeRouteGoogle(addresses);if(epoch!==generation.current)return;if(!r||r.route.length!==addresses.length||!r.route.every(valid)||new Set(r.route.map(a=>a.id)).size!==addresses.length)throw new Error();setAddresses(r.route);setResult(r);setRetry(n=>n+1);track('route_optimised');setNotice('Stop order updated. Check the route before setting off.');}catch(_){if(epoch===generation.current)setError('Could not optimise this route. Your manual order is unchanged. Retry when connected.');}finally{if(epoch===generation.current){lock.current=false;setBusy('');}}}
 function move(i,delta){const rows=[...addresses],j=i+delta;if(j<0||j>=rows.length)return;[rows[i],rows[j]]=[rows[j],rows[i]];change(rows);}
 function save(){if(!name.trim()||!addresses.length)return;try{const rows=[{id:crypto.randomUUID(),name:name.trim().slice(0,80),addresses},...saved].slice(0,30);localStorage.setItem(key,JSON.stringify(rows));setSaved(rows);setName('');setNotice('Route saved on this device for this account.');}catch(_){setError('Could not save on this device.');}}
 function removeSaved(id){if(!window.confirm('Delete this saved route?'))return;try{const rows=saved.filter(r=>r.id!==id);localStorage.setItem(key,JSON.stringify(rows));setSaved(rows);}catch(_){setError('Could not remove the saved route.');}}
 const navigationUrl=a=>'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(a.latitude+','+a.longitude)+'&travelmode=driving';
 return <div className="home-screen st-page route-page"><header className="home-row"><div><h1>Routes</h1><p className="home-muted">Build your stop order. Navigate with your maps app.</p></div><MapPin aria-hidden="true"/></header>{error&&<p role="alert" className="home-banner home-error">{error}<button className="home-text-button ml-3" onClick={()=>setError('')}>Dismiss</button></p>}{notice&&<p role="status" className="home-banner">{notice}</p>}
 <div className="route-layout"><div className="st-list"><section className="home-card"><label className="home-field">Search an address<input data-tour="route-search" autoComplete="off" value={query} disabled={!!busy} onChange={e=>{setQuery(e.target.value);setError('');}} placeholder="Street, address or postcode" aria-describedby="route-search-status"/></label><p id="route-search-status" role="status" className="home-muted text-sm mt-2">{searching?'Searching…':query.length>=3&&!suggestions.length?'No suggestions. Try a full address or postcode.':'Free address search and manual ordering.'}</p>{suggestions.length>0&&<ul className="route-suggestions">{suggestions.map((a,i)=><li key={a.placeId||i}><button disabled={!!busy} onClick={()=>add(a)}>{a.address}</button></li>)}</ul>}<button className="home-text-button" disabled={!!busy||addresses.length>=200} onClick={locate}><Locate size={18}/> {busy==='location'?'Getting location…':'Use my location as start'}</button></section>
 {!addresses.length?<div className="st-empty"><h2>Where are you starting?</h2><p>Add a start point, then your delivery stops. Addresses stay in this open route unless you choose to save it.</p></div>:<section className="home-card"><div className="home-row"><h2>{addresses.length} locations</h2><button className="home-text-button" disabled={!!busy} onClick={()=>{if(window.confirm('Clear this route?'))change([]);}}>Clear</button></div><p className="home-muted text-sm">First location stays as your start. Reorder stops manually for free.</p><ol className="route-stops">{addresses.map((a,i)=><li key={a.id}><div className="home-row"><strong className="route-number">{i+1}</strong><div className="st-grow"><strong>{a.address}</strong>{i===0&&<small className="st-muted block">Start</small>}</div></div><div className="st-actions"><button className="home-icon" aria-label={'Move stop '+(i+1)+' up'} disabled={i===0||!!busy} onClick={()=>move(i,-1)}><ArrowUp size={18}/></button><button className="home-icon" aria-label={'Move stop '+(i+1)+' down'} disabled={i===addresses.length-1||!!busy} onClick={()=>move(i,1)}><ArrowDown size={18}/></button><button className="home-icon" aria-label={'Remove stop '+(i+1)} disabled={!!busy} onClick={()=>change(addresses.filter(x=>x.id!==a.id))}><Trash2 size={18}/></button><a className="home-text-button" href={navigationUrl(a)} target="_blank" rel="noreferrer">Navigate here ↗</a></div></li>)}</ol><button className="home-primary w-full" disabled={addresses.length<2||!!busy} onClick={optimize}>{busy==='optimizing'?'Optimising…':status&&!status.isPro&&status.routeOptimizationUses>=3?'View Pro for optimisation':'Optimise stop order'}</button><p className="home-muted text-sm mt-2">{status?status.isPro?'Full optimisation included with Pro':`${Math.max(0,3-(status.routeOptimizationUses||0))} free full-route optimisations left`:'Trial status unavailable; availability is checked by the server.'}</p>{!status&&<button className="home-text-button" onClick={()=>setRetry(n=>n+1)}>Refresh trial status</button>}</section>}
 <details className="home-card"><summary>Saved routes · This device</summary><label className="home-field">Route name<input value={name} maxLength={80} onChange={e=>setName(e.target.value)}/></label><button className="home-secondary w-full mt-3" disabled={!name.trim()||!addresses.length||!!busy} onClick={save}>Save this route</button><p className="home-muted text-sm mt-3">Saving retains these addresses on this device. Delete routes when you no longer need them.</p>{saved.map(r=><div className="home-row py-3" key={r.id}><button className="home-text-button" disabled={!!busy} onClick={()=>{if(!addresses.length||window.confirm('Replace the current route?'))change(r.addresses);}}>{r.name} · {r.addresses.length} locations</button><button className="home-icon" aria-label={'Delete saved route '+r.name} onClick={()=>removeSaved(r.id)}><Trash2 size={18}/></button></div>)}</details></div>
 <section className="home-card route-map-panel"><h2>Your route</h2><p className="home-muted text-sm">{result?`${(result.totalDistanceKm*.621371).toFixed(1)} miles · About ${result.totalDurationMin} minutes driving`:'Pins show your stop order. Connecting lines are not road directions.'}</p><div className="route-map">{addresses.length?process.env.REACT_APP_GOOGLE_MAPS_API_KEY?<GoogleRouteMap addresses={addresses} fallback={<RouteMap addresses={addresses}/>}/>:<RouteMap addresses={addresses}/>:<div className="st-empty"><MapPin className="mx-auto"/><p>Your locations will appear here.</p></div>}</div><p className="home-muted text-sm">Check access restrictions and road conditions in your navigation app. Navigation opens one selected location at a time.</p></section></div></div>;
}
