import React,{useMemo,useState,useEffect} from 'react';
import {Link,useLocation} from 'react-router-dom';
import {useData} from '../contexts/DataContext';
import {isoDate,listPeriods} from '../features/payperiod/periods';
import {validRange} from '../features/money/moneyModel';
import {money,pennies} from '../features/home/homeModel';
import {trackProductEvent as track} from '../services/productAnalytics';
export function insightSummary(logs,period){const rows=logs.filter(r=>r.date>=period.start&&r.date<=period.end&&([r.quantity,r.stops,r.hours,r.miles,r.total].some(v=>Number(v)>0)));const days=[...new Set(rows.map(r=>r.date))].sort().map(date=>{const rs=rows.filter(r=>r.date===date);return {date,stops:rs.reduce((s,r)=>s+(Number(r.stops)||0),0),excess:rs.reduce((s,r)=>s+(r.excessParcels!=null?Number(r.excessParcels)||0:r.totalParcels!=null?Math.max(0,Number(r.totalParcels)-(Number(r.stops)||0)):0),0),gross:rs.every(r=>Number.isFinite(Number(r.total))&&r.total!=null&&r.total!=='')?rs.reduce((s,r)=>s+pennies(Number(r.total)),0):null};});return {days,stops:days.reduce((s,d)=>s+d.stops,0),excess:days.reduce((s,d)=>s+d.excess,0),gross:days.every(d=>d.gross!=null)?days.reduce((s,d)=>s+d.gross,0):null};}
export default function StatsPage(){
 const {logs=[],payPeriodAnchor,loading,loadError}=useData(),location=useLocation();const [selected,setSelected]=useState(null);const today=isoDate(new Date());
 const periods=useMemo(()=>listPeriods(logs,payPeriodAnchor||today,14),[logs,payPeriodAnchor,today]);const requested=validRange(location.state)?{...location.state,id:location.state.start+'_'+location.state.end}:null;const period=selected||requested||periods[0];const choices=periods.some(p=>p.id===period.id)?periods:[period,...periods];
 const summary=insightSummary(logs,period),index=periods.findIndex(p=>p.id===period.id),previous=periods[index+1],prior=previous?insightSummary(logs,previous):null;const n=summary.days.length;const hidden=(()=>{try{return localStorage.getItem('home-hide-money')==='1';}catch(_){return false;}})();const cash=v=>hidden?'••••':v==null?'Unavailable':money(v/100);const max=Math.max(1,...summary.days.map(d=>d.stops));
 useEffect(()=>{track('insights_viewed');},[]);
 return <div className="home-screen st-page"><header><h1>Insights</h1><p className="home-muted">A simple view of your recorded work.</p></header><nav className="st-tabs" aria-label="Money sections"><Link to="/app/money" state={period}>Overview</Link><Link to="/app/money/expenses" state={period}>Expenses</Link><Link to="/app/stats" state={period} aria-current="page">Insights</Link></nav><label className="home-field">Pay period<select data-tour="insights-period" value={period.id} onChange={e=>setSelected(choices.find(p=>p.id===e.target.value))}>{choices.map(p=><option key={p.id} value={p.id}>{p.start} – {p.end}</option>)}</select></label>
 {loading?<div className="home-skeleton" role="status" aria-label="Loading insights"/>:loadError?<p className="home-banner" role="alert">Work records could not be loaded.</p>:!n?<div className="st-empty"><h2>No work recorded this period</h2><p>Your trends will appear as you log days.</p><Link className="home-text-button" to="/app/dashboard">Log work</Link></div>:<><section className="st-metrics">{[[n,'Days worked'],[(summary.stops/n).toFixed(1),'Average stops/day'],[(summary.excess/n).toFixed(1),'Average excess parcels/day'],[cash(summary.gross==null?null:Math.round(summary.gross/n)),'Average gross earnings/day · Estimated']].map(([v,l])=><div className="home-card" key={l}><strong>{v}</strong><p>{l}</p></div>)}</section><section className="home-card"><h2>Stops by day</h2><p className="home-muted text-sm">Recorded days only. Missing days are not treated as days off.</p><div className="insight-bars">{summary.days.map(d=><div key={d.date}><span>{d.date.slice(5)}</span><div><span style={{width:(d.stops/max*100)+'%'}}/></div><strong>{d.stops}</strong></div>)}</div><details><summary>View daily figures</summary><div className="st-table-wrap"><table className="st-table"><thead><tr><th>Date</th><th>Stops</th><th>Gross · Estimated</th></tr></thead><tbody>{summary.days.map(d=><tr key={d.date}><td>{d.date}</td><td>{d.stops}</td><td>{cash(d.gross)}</td></tr>)}</tbody></table></div></details></section><section className="home-card"><h2>Previous period comparison</h2>{prior?.days.length?<><p className="home-muted">{previous.start} – {previous.end}</p><dl className="money-waterfall"><div><dt>Days worked</dt><dd>{n} vs {prior.days.length}</dd></div><div><dt>Average stops/day</dt><dd>{(summary.stops/n).toFixed(1)} vs {(prior.stops/prior.days.length).toFixed(1)}</dd></div><div><dt>Gross earnings · Estimated</dt><dd>{cash(summary.gross)} vs {cash(prior.gross)}</dd></div></dl>{period.end>=today&&<p className="home-banner">This period is still in progress. Full-period totals are not yet directly comparable.</p>}</>:<p className="home-muted mt-3">Log work in another period to see a comparison.</p>}</section></>}
 <Link className="home-secondary" to="/app/periods">View pay periods</Link></div>;
}
