import React,{useState} from 'react';
import StatementWorkDetails from './StatementWorkDetails';
import {money,pennies} from '../features/home/homeModel';
import {trackProductEvent as track} from '../services/productAnalytics';
export function comparisonLines(review,summary){
 const fields=[['Work earnings','grossPence',summary.gross],['Contractor fee','feePence',summary.fee],['Contractor charges','chargesPence',pennies(summary.costs.contractor)]];
 return fields.map(([label,key,expected])=>({label,expected,statement:review?.[key],difference:Number.isSafeInteger(expected)&&Number.isSafeInteger(review?.[key])?review[key]-expected:null}));
}
export default function StatementComparison({period,expected,statement,summary,review,workDetails,saved,resolved,stale,unavailable,hidden,saving,error,onSave,onEdit,onBack,onResolve}){
 const [confirm,setConfirm]=useState(false),[reason,setReason]=useState('');
 const cash=v=>hidden?'••••':money(v/100),difference=statement-expected;
 const lines=comparisonLines(review,summary);
 return <section className="home-screen comparison-page">
 <header><h1>Compare statement</h1><p className="home-muted">{period.start} – {period.end}</p></header><span className="money-badge">{resolved?'Period reconciled':saved?'Checked · Unresolved':'Preview · Not saved'}</span>
 <section className={'home-card comparison-hero '+(difference?'comparison-warning':'comparison-match')}><p>{unavailable?'Comparison unavailable':difference===0?'Payout totals match':'Statement is'}</p><h2>{unavailable?'Check your records':difference===0?'No payout difference':hidden?'Different from your estimate':`${cash(Math.abs(difference))} ${difference<0?'lower':'higher'}`}</h2><p className="home-muted">{difference!==0?'than your expected contractor payout':'Matching totals do not prove every line item matches.'}</p><dl className="money-waterfall"><div><dt>Expected · Estimated</dt><dd>{unavailable?'Unavailable':cash(expected)}</dd></div><div><dt>Statement · Reviewed</dt><dd>{cash(statement)}</dd></div></dl><p className="home-muted text-sm">Before your own business expenses and personal tax. Compared on the VAT basis you confirmed.</p></section>
 <section className="home-card"><h2>Where the difference appears</h2>{lines.every(l=>l.difference==null)?<p className="home-muted mt-3">Totals-only comparison. Add statement details to explain the difference.</p>:lines.map(l=><details className="money-details" key={l.label} onToggle={e=>{if(e.currentTarget.open)track('comparison_detail_opened');}}><summary>{l.label} <span>{l.difference==null?'Not compared':l.difference===0?'No difference':`${l.difference>0?'+':''}${cash(l.difference)}`}</span></summary><dl className="money-waterfall"><div><dt>Your records</dt><dd>{l.expected==null?'Unavailable':cash(l.expected)}</dd></div><div><dt>Statement</dt><dd>{l.statement==null?'Not entered':cash(l.statement)}</dd></div></dl>{l.label!=='Work earnings'&&l.difference>0&&<p className="home-muted text-sm">Higher charges reduce your payout.</p>}</details>)}{review?.charges?.length>0&&<details className="money-details"><summary>Reviewed statement charges</summary>{review.charges.map((c,i)=><p className="home-row py-2" key={i}><span>{c.label}</span><strong>{cash(c.amountPence)}</strong></p>)}<p className="home-muted text-sm">These are statement figures. No expense records were added or changed.</p></details>}</section>
 {workDetails&&<section className="home-card"><StatementWorkDetails value={workDetails} rows={summary.rows} readOnly hidden={hidden}/></section>}
 {stale&&<p role="alert" className="home-banner">Records changed since this preview. Edit statement figures to review the updated comparison.</p>}
 {resolved&&<p role="status" className="home-banner">You marked this comparison resolved. This does not confirm that payment arrived.</p>}
 {error&&<p role="alert" className="home-error">{error}</p>}
 {!saved?<button className="home-primary w-full" disabled={saving||stale||unavailable} onClick={onSave}>{saving?'Saving check…':'Confirm and save check'}</button>:!resolved&&!confirm?<button className="home-secondary w-full" disabled={stale||unavailable} onClick={()=>{setConfirm(true);track('reconciliation_started');}}>Mark comparison resolved</button>:null}
 {saved&&!resolved&&confirm&&<section className="home-card space-y-3"><h2>Resolve this comparison?</h2><p className="home-muted">Only continue once you have checked the difference and are satisfied with the outcome. The original figures remain in your records.</p><label className="home-field">Outcome<select value={reason} onChange={e=>setReason(e.target.value)}><option value="">Choose an outcome</option><option value="figures_verified">Figures verified and accepted</option><option value="explained_difference">Difference explained and accepted</option></select></label><button className="home-primary w-full" disabled={!reason||saving||stale||unavailable} onClick={()=>onResolve(reason)}>{saving?'Saving resolution…':'Confirm resolved'}</button><button className="home-text-button" disabled={saving} onClick={()=>setConfirm(false)}>Keep unresolved</button></section>}
 <button className="home-secondary w-full" disabled={saving} onClick={onEdit}>Edit statement figures</button><button className="home-text-button" disabled={saving} onClick={onBack}>Back to Check Pay</button><p className="home-muted text-sm">Saving records this check. Payment receipt and personal taxes are separate.</p>
 </section>;
}
