import React,{useMemo,useState} from "react";
import {useNavigate} from "react-router-dom";
import {useData} from "../contexts/DataContext";
import {getPeriodForDate,summarizePeriod,listPeriods} from "../features/payperiod/periods";
import {Money} from "./ui/money";
import {BarChart3,CalendarDays,Package,Trophy,ShieldCheck,ChevronRight} from "lucide-react";
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const fmt=d=>new Date(d+"T12:00:00").toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"});
export default function StatsPage(){
 const nav=useNavigate(); const {logs=[],payPeriodAnchor,periodRecords={}}=useData(); const today=iso(new Date()); const anchor=payPeriodAnchor||today;
 const periods=useMemo(()=>listPeriods(logs,anchor,8),[logs,anchor]); const [selected,setSelected]=useState(periods[0]?.id||"");
 const p=periods.find(x=>x.id===selected)||periods[0]||getPeriodForDate(anchor,new Date()); const s=useMemo(()=>summarizePeriod(logs,p),[logs,p]);
 const idx=periods.findIndex(x=>x.id===p.id); const prev=periods[idx+1]; const prevS=prev?{stops:prev.stops,expected:prev.expected,daysLogged:prev.daysLogged}:null;
 const days=[...s.logs].sort((a,b)=>a.date.localeCompare(b.date)); const busiest=[...days].sort((a,b)=>(b.stops||0)-(a.stops||0))[0]; const avg=s.daysLogged?Math.round(s.stops/s.daysLogged):0; const max=Math.max(1,...days.map(x=>Number(x.stops)||0)); const rec=periodRecords[p.id];
 const delta=(a,b)=>b?((a-b)/b)*100:null; const dStops=prevS?delta(s.stops,prevS.stops):null; const dEarn=prevS?delta(s.expected,prevS.expected):null;
 return <div className="mx-auto max-w-2xl space-y-4 pb-24 pt-2">
  <div className="flex items-end justify-between gap-3"><div><h1 className="text-3xl font-bold">Insights</h1><p className="mt-1 text-sm text-[#8e9ab2]">Your work at a glance.</p></div><select aria-label="Pay period" value={p.id} onChange={e=>setSelected(e.target.value)} className="max-w-[190px] rounded-xl border border-[#3b4770] bg-[#111827] px-3 py-2 text-xs text-white outline-none focus:border-[#7567ff]">{periods.map(x=><option key={x.id} value={x.id}>{fmt(x.start)} – {fmt(x.end)}</option>)}</select></div>
  <div className="grid grid-cols-3 gap-2"><div className="rounded-2xl border border-[#202a3d] bg-[#111827] p-3 text-center"><Package className="mx-auto mb-2 h-4 w-4 text-[#9b91ff]"/><div className="text-lg font-bold">{s.stops.toLocaleString("en-GB")}</div><div className="text-[10px] text-[#7f8ba3]">Total stops</div></div><div className="rounded-2xl border border-[#202a3d] bg-[#111827] p-3 text-center"><div className="mb-2 text-[10px] font-bold text-[#9b91ff]">EXPECTED</div><div className="text-base font-bold"><Money amount={s.expected}/></div><div className="text-[10px] text-[#7f8ba3]">Earnings</div></div><div className="rounded-2xl border border-[#202a3d] bg-[#111827] p-3 text-center"><CalendarDays className="mx-auto mb-2 h-4 w-4 text-[#9b91ff]"/><div className="text-lg font-bold">{s.daysLogged}</div><div className="text-[10px] text-[#7f8ba3]">Work days</div></div></div>
  <section className="rounded-[22px] border border-[#243149] bg-[#0d1624] p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 font-bold"><BarChart3 className="h-5 w-5 text-emerald-400"/>Stops per day</h2><p className="mt-1 text-xs text-[#7f8ba3]">Your workload across this period.</p></div><div className="text-right text-[11px] text-[#8e9ab2]"><div>Average <b className="text-white">{avg}</b></div>{busiest&&<div className="mt-1">Busiest <b className="text-white">{busiest.stops}</b></div>}</div></div><div data-no-swipe className="mt-5 flex h-40 items-end gap-1 overflow-x-auto pb-5">{days.length?days.map(d=><div key={d.id||d.date} title={`${fmt(d.date)} · ${d.stops||0} stops`} className="flex h-full min-w-[18px] flex-1 items-end"><div className="w-full rounded-t-md bg-gradient-to-t from-[#6657f5] to-emerald-400 transition-all duration-500" style={{height:`${Math.max(5,((Number(d.stops)||0)/max)*100)}%`}}/></div>):<div className="m-auto text-sm text-[#6f7b92]">No entries in this period yet.</div>}</div></section>
  <section className="rounded-2xl border border-[#202a3d] bg-[#111827] p-4"><div className="flex items-center justify-between"><div><h2 className="font-bold">Period comparison</h2><p className="text-xs text-[#7f8ba3]">Compared with the previous 4 weeks.</p></div>{prev&&<span className="text-[10px] text-[#7f8ba3]">{fmt(prev.start)} – {fmt(prev.end)}</span>}</div><div className="mt-4 grid grid-cols-3 divide-x divide-[#26314a] text-center"><div><b>{s.stops.toLocaleString()}</b><div className="text-[10px] text-[#7f8ba3]">stops</div>{dStops!==null&&<div className="mt-1 text-[10px] text-[#9b91ff]">{dStops>=0?"+":""}{dStops.toFixed(1)}%</div>}</div><div><b><Money amount={s.expected}/></b><div className="text-[10px] text-[#7f8ba3]">expected</div>{dEarn!==null&&<div className="mt-1 text-[10px] text-[#9b91ff]">{dEarn>=0?"+":""}{dEarn.toFixed(1)}%</div>}</div><div><b>{s.daysLogged}</b><div className="text-[10px] text-[#7f8ba3]">work days</div>{prevS&&<div className="mt-1 text-[10px] text-[#9b91ff]">vs {prevS.daysLogged}</div>}</div></div>{p.id===periods[0]?.id&&new Date()<=new Date(p.end+"T23:59:59")&&<p className="mt-3 text-[10px] leading-4 text-[#69758d]">Current period is still in progress, so totals may be lower than a completed period.</p>}</section>
  {rec?.status==="reconciled"&&<button onClick={()=>nav("/app/check-pay",{state:{periodId:p.id}})} className="flex w-full items-center gap-3 rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-4 text-left"><ShieldCheck className="text-emerald-400"/><span className="flex-1"><b className="block text-sm">{Number(rec.differenceStops)===0&&Number(rec.differenceAmount)===0?"Statement matched your records":"Statement comparison complete"}</b><span className="text-xs text-[#8e9ab2]">{Number(rec.differenceStops)||0} stop difference · <Money amount={Number(rec.differenceAmount)||0}/></span></span><ChevronRight className="h-4 w-4 text-emerald-400"/></button>}
  <section><div className="mb-2 flex items-center justify-between"><h2 className="font-bold">Recent periods</h2><button onClick={()=>nav("/app/periods")} className="text-xs font-semibold text-[#9b91ff]">View all</button></div><div className="space-y-2">{periods.slice(0,3).map(x=><button key={x.id} onClick={()=>setSelected(x.id)} className="flex w-full items-center gap-3 rounded-xl border border-[#202a3d] bg-[#111827] p-3 text-left"><Trophy className="h-4 w-4 text-[#7567ff]"/><span className="flex-1"><span className="block text-xs font-semibold">{fmt(x.start)} – {fmt(x.end)}</span><span className="text-[10px] text-[#7f8ba3]">{x.stops.toLocaleString()} stops · <Money amount={x.expected}/></span></span><ChevronRight className="h-4 w-4 text-[#69758d]"/></button>)}</div></section>
 </div>;
}